on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: harupy/pyspark-util
      volumes:
        - .:/pyspark-util
    steps:
      - uses: actions/checkout@v1
      - name: Run test
        run: |
          ls
          ./tools/test.sh
