on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: harupy/pyspark-util
      volumes:
        - .:/pyspark-util
    steps:
      - name: Run test
        run: ./tools/test.sh
